In [1]:
import numpy as np

In [2]:
np.array([0,2,4,6,7])

array([0, 2, 4, 6, 7])

In [3]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [4]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [5]:
np.zeros((5,1))

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [7]:
np.zeros((1,5))

array([[ 0.,  0.,  0.,  0.,  0.]])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [10]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [11]:
np.random.random(5)

array([ 0.09496911,  0.52255169,  0.0083858 ,  0.39742101,  0.86853026])

In [12]:
x = np.array( [  1.0,  2.0,  3.0,  4.0,  5.0 ] )
y = np.array( [ 10.0, 20.0, 30.0, 40.0, 50.0 ] )

In [16]:
z = x + y
z

array([ 11.,  22.,  33.,  44.,  55.])

In [17]:
z = x - y
z

array([ -9., -18., -27., -36., -45.])

In [18]:
z = x * y
z

array([  10.,   40.,   90.,  160.,  250.])

In [19]:
a = np.dot( x, y )
a

550.0

In [22]:
y = x + a
y

array([ 4.14,  5.14,  6.14,  7.14,  8.14])

In [23]:
y = x - a
y

array([-2.14, -1.14, -0.14,  0.86,  1.86])

In [24]:
y = x * a
y

array([  3.14,   6.28,   9.42,  12.56,  15.7 ])

In [25]:
y = x / a
y

array([ 0.31847134,  0.63694268,  0.95541401,  1.27388535,  1.59235669])

In [28]:
a = np.linalg.norm( x )
a

7.416198487095663

In [29]:
x = x / a
x

array([ 0.13483997,  0.26967994,  0.40451992,  0.53935989,  0.67419986])

In [33]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)]) # note mix of tuple and lists, and types
x

array([[ 1.+0.j,  2.+0.j],
       [ 0.+0.j,  0.+0.j],
       [ 1.+1.j,  3.+0.j]])

In [34]:
x = np.array([[ 1.+0.j, 2.+0.j], [ 0.+0.j, 0.+0.j], [ 1.+1.j, 3.+0.j]])
x

array([[ 1.+0.j,  2.+0.j],
       [ 0.+0.j,  0.+0.j],
       [ 1.+1.j,  3.+0.j]])

In [35]:
np.arange(2, 10, dtype=np.float)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [36]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [41]:
shape=5,10,20

In [43]:
np.random.rand(5,10,20)

array([[[ 0.96923123,  0.99069671,  0.20690612,  0.57313699,  0.50903306,
          0.51810669,  0.77232017,  0.39530807,  0.13111252,  0.17804191,
          0.18711371,  0.81831357,  0.47472591,  0.30373616,  0.74889867,
          0.87130781,  0.24859618,  0.22802289,  0.14576909,  0.88000606],
        [ 0.18017005,  0.59899712,  0.09408556,  0.85245825,  0.36901681,
          0.07764766,  0.86848221,  0.4476892 ,  0.19020813,  0.14693164,
          0.91528083,  0.5444767 ,  0.00333156,  0.55054506,  0.77366938,
          0.74066883,  0.08715451,  0.67199179,  0.85266807,  0.93497022],
        [ 0.13748712,  0.4369838 ,  0.32166098,  0.34174136,  0.13403881,
          0.39783124,  0.54414202,  0.09899172,  0.18078868,  0.32938646,
          0.36587632,  0.16440074,  0.67806289,  0.25325073,  0.22006194,
          0.83800495,  0.14392972,  0.10087374,  0.03221316,  0.85560528],
        [ 0.5055309 ,  0.11015347,  0.59825511,  0.23534271,  0.26296549,
          0.49870151,  0.63200179, 

In [44]:
np.random.randn(5,10,20)

array([[[  8.89319543e-03,  -2.76955797e+00,   1.45204402e+00,
           5.91885234e-01,   5.36791618e-01,   1.35317794e+00,
           9.34233358e-01,  -8.35933619e-01,  -1.57610634e-01,
           1.49472599e+00,  -5.06673898e-01,   1.42028191e+00,
           5.09991667e-02,  -3.99505520e-01,   1.51423610e-01,
           7.06961133e-01,   2.74577606e+00,   5.68596523e-03,
           7.63648253e-01,   3.43271443e-02],
        [  1.43615155e-01,   1.24233823e+00,  -3.85405143e-01,
          -1.67022104e+00,   2.75570221e-01,   4.42805147e-01,
          -1.22533615e-01,   1.75358540e+00,   1.67758505e+00,
          -1.83878836e+00,  -1.08333463e+00,   5.55483615e-01,
          -5.04421920e-01,  -7.58651380e-01,  -1.44311207e+00,
          -6.87499793e-01,   5.58998738e-01,  -2.80230533e-01,
           7.92967991e-01,   3.06297208e-01],
        [ -7.40291391e-01,  -2.38919882e-01,  -7.29555134e-01,
           1.35274878e-01,   2.53306544e+00,  -2.79939244e-02,
           2.67619881e-01,

In [45]:
np.random.randint(5, size=(2, 4))

array([[3, 4, 4, 1],
       [3, 4, 1, 4]])

In [50]:
np.random.random_sample()

0.35923247998034247

In [49]:
np.random.random_sample((5,))

array([ 0.80967367,  0.30418545,  0.81867098,  0.56272631,  0.0071744 ])

In [51]:
5 * np.random.random_sample((3, 2)) - 5

array([[-1.48458321, -0.90316504],
       [-2.6864589 , -1.59366061],
       [-0.67045244, -1.21975207]])

In [52]:
np.random.choice(5, 3) #This is equivalent to np.random.randint(0,5,3)

array([4, 1, 3])

In [53]:
np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 2, 3])

In [54]:
np.random.choice(5, 3, replace=False) #This is equivalent to np.random.permutation(np.arange(5))[:3]

array([4, 0, 3])

In [55]:
np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 2, 0])

In [56]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['rabbit', 'Christopher', 'pooh', 'piglet', 'rabbit'], 
      dtype='|S11')

In [57]:
np.random.bytes(10)

'\xb1\xff1\x17BT\x0f\xbb\x12m'

In [60]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([8, 9, 3, 4, 1, 2, 6, 7, 5, 0])

In [61]:
# This function only shuffles the array along the first index of a multi-dimensional array:
arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [62]:
np.random.permutation(10)

array([2, 7, 8, 3, 6, 1, 9, 5, 0, 4])

In [63]:
np.random.permutation([1, 4, 9, 12, 15])

array([ 4,  9, 12,  1, 15])

In [64]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [65]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
np.dot(3, 4)

12

In [67]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [68]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [79]:
x = np.arange(10)
x.shape = (2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
 x[1,3]

8

In [81]:
x[1,-1]

9

In [82]:
x[0]

array([0, 1, 2, 3, 4])

In [83]:
x[0][2]
#So note that x[0,2] = x[0][2] though the second case is more inefficient as a 
#new temporary array is created after the first index that is subsequently indexed by 2.

2

In [84]:
x = np.arange(10)

In [85]:
x[2:5]

array([2, 3, 4])

In [86]:
x[:-7]

array([0, 1, 2])

In [87]:
x[-10]

0

In [88]:
x[1:7:2]

array([1, 3, 5])

In [90]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [91]:
np.arange(3*4*5*6)[::-1]

array([359, 358, 357, 356, 355, 354, 353, 352, 351, 350, 349, 348, 347,
       346, 345, 344, 343, 342, 341, 340, 339, 338, 337, 336, 335, 334,
       333, 332, 331, 330, 329, 328, 327, 326, 325, 324, 323, 322, 321,
       320, 319, 318, 317, 316, 315, 314, 313, 312, 311, 310, 309, 308,
       307, 306, 305, 304, 303, 302, 301, 300, 299, 298, 297, 296, 295,
       294, 293, 292, 291, 290, 289, 288, 287, 286, 285, 284, 283, 282,
       281, 280, 279, 278, 277, 276, 275, 274, 273, 272, 271, 270, 269,
       268, 267, 266, 265, 264, 263, 262, 261, 260, 259, 258, 257, 256,
       255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243,
       242, 241, 240, 239, 238, 237, 236, 235, 234, 233, 232, 231, 230,
       229, 228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217,
       216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204,
       203, 202, 201, 200, 199, 198, 197, 196, 195, 194, 193, 192, 191,
       190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 17

In [73]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))

array([[[[359, 358, 357],
         [356, 355, 354],
         [353, 352, 351],
         [350, 349, 348],
         [347, 346, 345],
         [344, 343, 342]],

        [[341, 340, 339],
         [338, 337, 336],
         [335, 334, 333],
         [332, 331, 330],
         [329, 328, 327],
         [326, 325, 324]],

        [[323, 322, 321],
         [320, 319, 318],
         [317, 316, 315],
         [314, 313, 312],
         [311, 310, 309],
         [308, 307, 306]],

        [[305, 304, 303],
         [302, 301, 300],
         [299, 298, 297],
         [296, 295, 294],
         [293, 292, 291],
         [290, 289, 288]]],


       [[[287, 286, 285],
         [284, 283, 282],
         [281, 280, 279],
         [278, 277, 276],
         [275, 274, 273],
         [272, 271, 270]],

        [[269, 268, 267],
         [266, 265, 264],
         [263, 262, 261],
         [260, 259, 258],
         [257, 256, 255],
         [254, 253, 252]],

        [[251, 250, 249],
         [248, 247, 246]

In [71]:
np.dot(a, b)[2,3,2,1,2,2]

ValueError: shapes (3,4,5,6) and (2,2) not aligned: 6 (dim 3) != 2 (dim 0)